@startuml
title
 Diagram Test3
end title

class Order3
{
}
note right of Order3
Note from annotation
end note
class CompanyInfo
{
    +string Name
}
class OrderItem3
{
}
note left of OrderItem3
Note from UmlNote
end note

Order3 o-right-> CompanyInfo:Customer
note on link  #ffe0f0
Note on relation
from UmlRelationAtribute
end note
' MyId
Order3 "bla 1" *-[#yellow]up-|> "bla 2" CompanyInfo:Customer2
Order3 *-----{ OrderItem3:Items
@enduml
