@startuml
title
 Diagram Generics
end title

class GenericBase
{
}
class "Generic1<T>"
{
}
class "Generic2<TModel,TElement>"
{
}
class NonGeneric
{
    Dictionary<string,double> GenericDic
}

"Generic1<T>" -up-|> GenericBase
"Generic2<TModel,TElement>" -up-|> "Generic1<T>"
NonGeneric -up-|> "Generic2<TModel,TElement>"
@enduml
